### ISSUE TITLE
Suggestion on improved #warning text

### ISSUE THREAD

**Issue by Rob58329** [tobozo/ESP32-PsRamFS#13]
@tobozo: This library was just what I was looking for - thank you!  (PS. works on the ESP32-S3 too.)

PS. You might consider modifying "pfs.c" to something like:
```
#if defined BOARD_HAS_PSRAM
  #warning "Will use PSRAM or heap"
#elif !defined CONFIG_SPIRAM_SUPPORT
  #warning "No SPIRAM detected, will use heap"
#endif
```

Also, it would be good if one could override the `#define FPSRAM_PARTITION_SIZE 0.5` line (in "PSRamFS.h") by pre-defining the variable to say `#define FPSRAM_PARTITION_SIZE 0.25` in my main sketch, rather than having to modify the "PSRamFS.h" file.  However I can't find a way of defining the variable in my sketch so that is visible to the "PSRamFS.h" definition?!

**Comment by tobozo** [comment]
hi, thanks for your feedback :+1: 

psram and spiram may be different things depending on the device and sdk version so I've merged both conditions and modified the detection logic.

you can now call this before PsRamFS.begin() to adjust the partition size:

    PSRamFS.setPartitionSize( ESP.getFreePsram()/2 );
