### ISSUE TITLE
Handle FS using VFS POSIX API

### ISSUE THREAD

**Issue by ianwillianb** [tobozo/ESP32-PsRamFS#5]
Is POSIX style VFS API supported? I want to use this library in conjunction with SQLite 3 database for ESP32, all running in PSRAM (allocations for SQLite and the database files itself).

By the way, awesome project 😎

**Comment by tobozo** [comment]
hello @ianwillianb and thanks for your feedback :+1: 

PSRamFS vfs compliance has been tested with [rrdtools](https://github.com/lbernstone/rrdtool_ESP32) and should work as is with SQLiteEsp32.

Please let me know how if you face any issue.

**Comment by ianwillianb** [comment]
Hello @tobozo, thanks for the quick reply.
I'll definitely try it out 🙂
